config/routes.rb
Rails.application.routes.draw do
  

  resources :performance_evaluations
  resources :employees
  
  resources :performance_commitments do
    resources :comments
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
has_many :performance_evaluations

end

app/models/performance_commitment.rb
class PerformanceCommitment < ApplicationRecord
    belongs_to :performance_evaluation
end

app/models/performance_evaluation.rb
class PerformanceEvaluation < ApplicationRecord
    belongs_to :employee
    has_many :performance_commitments, inverse_of: :performance_evaluation
    accepts_nested_attributes_for :performance_commitments, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    puts "+++++++++++++"
    puts params
    puts "+++++++++++++"
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name)
    end
end

app/controllers/performance_commitments_controller.rb
class PerformanceCommitmentsController < ApplicationController
  def index
    puts "hellllo"
  end

  def create
  end

  def new
  end

  def destroy
  end

  def show
    puts "hola"
  end
end

app/controllers/performance_evaluations_controller.rb
class PerformanceEvaluationsController < ApplicationController
  before_action :set_performance_evaluation, only: [:show, :edit, :update, :destroy]

  # GET /performance_evaluations
  # GET /performance_evaluations.json
  def index
    @performance_evaluations = PerformanceEvaluation.all
  end

  # GET /performance_evaluations/1
  # GET /performance_evaluations/1.json
  def show
  end

  # GET /performance_evaluations/new
  def new
    #cambiar el find por el params[:employee_id]
    #@employe = Employee.find(1)
    #@performance_evaluation = @employe.performance_evaluation.build
    @performance_evaluation = PerformanceEvaluation.new
    @commitment = @performance_evaluation.performance_commitments.build
  #@commitment.employee = @employee
  end

  # GET /performance_evaluations/1/edit
  def edit
  end

  # POST /performance_evaluations
  # POST /performance_evaluations.json
  def create
    @employee = Employee.find(1)
    @performance_evaluation = @employee.performance_evaluations.build(performance_evaluation_params)
    #@performance_evaluation = PerformanceEvaluation.new(performance_evaluation_params)

    respond_to do |format|
      if @performance_evaluation.save
        format.html { redirect_to @performance_evaluation, notice: 'Performance evaluation was successfully created.' }
        format.json { render :show, status: :created, location: @performance_evaluation }
      else
        format.html { render :new }
        format.json { render json: @performance_evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /performance_evaluations/1
  # PATCH/PUT /performance_evaluations/1.json
  def update
    respond_to do |format|
      if @performance_evaluation.update(performance_evaluation_params)
        format.html { redirect_to @performance_evaluation, notice: 'Performance evaluation was successfully updated.' }
        format.json { render :show, status: :ok, location: @performance_evaluation }
      else
        format.html { render :edit }
        format.json { render json: @performance_evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /performance_evaluations/1
  # DELETE /performance_evaluations/1.json
  def destroy
    @performance_evaluation.destroy
    respond_to do |format|
      format.html { redirect_to performance_evaluations_url, notice: 'Performance evaluation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_performance_evaluation
      @performance_evaluation = PerformanceEvaluation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def performance_evaluation_params
      params.require(:performance_evaluation).permit(:title, :due_date,
        :performance_commitments_attributes => [:commitment])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/performance_commitments_helper.rb
module PerformanceCommitmentsHelper
end

app/helpers/performance_evaluations_helper.rb
module PerformanceEvaluationsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<%= link_to 'add',  new_performance_commitment_comment_path %>
</table>

<br>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>     <%#= link_to 'crear evaluacion',  %>  </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nuevo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/performance_commitments/create.html.erb
<h1>PerformanceCommitments#create</h1>
<p>Find me in app/views/performance_commitments/create.html.erb</p>

app/views/performance_commitments/destroy.html.erb
<h1>PerformanceCommitments#destroy</h1>
<p>Find me in app/views/performance_commitments/destroy.html.erb</p>

app/views/performance_commitments/index.html.erb
<h1>PerformanceCommitments#index</h1>
<p>Find me in app/views/performance_commitments/index.html.erb</p>

app/views/performance_commitments/new.html.erb
<h1>PerformanceCommitments#new</h1>
<p>Find me in app/views/performance_commitments/new.html.erb</p>

app/views/performance_commitments/show.html.erb
<h1>PerformanceCommitments#show</h1>
<p>Find me in app/views/performance_commitments/show.html.erb</p>

app/views/performance_evaluations/_commitment_fields.html.erb
<div class="nested-fields">
<div class="field">
<%= f.label :commitment %>
<%= f.text_field :commitment %>
</div>
</div>

app/views/performance_evaluations/_form.html.erb
<%= form_for @performance_evaluation do |form| %>
  <% if performance_evaluation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(performance_evaluation.errors.count, "error") %> prohibited this performance_evaluation from being saved:</h2>

      <ul>
      <% performance_evaluation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.date_select :due_date %>
  </div>

<h3>commitments</h3>
<div id="commitments">

<%= form.fields_for :performance_commitments do |commitment| %>
 
 <%= render 'commitment_fields', f: commitment %>
<% end %>
</div>

<div class="links">
<%= link_to_add_association 'add', form, :performance_commitments, partial: 'commitment_fields'  %>
</div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/performance_evaluations/edit.html.erb
<h1>Editing Performance Evaluation</h1>

<%= render 'form', performance_evaluation: @performance_evaluation %>

<%= link_to 'Show', @performance_evaluation %> |
<%= link_to 'Back', performance_evaluations_path %>

app/views/performance_evaluations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Performance Evaluations</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Due date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @performance_evaluations.each do |performance_evaluation| %>
      <tr>
        <td><%= performance_evaluation.title %></td>
        <td><%= performance_evaluation.due_date %></td>
        <td><%= link_to 'Show', performance_evaluation %></td>
        <td><%= link_to 'Edit', edit_performance_evaluation_path(performance_evaluation) %></td>
        <td><%= link_to 'Destroy', performance_evaluation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Performance Evaluation', new_performance_evaluation_path %>

app/views/performance_evaluations/new.html.erb
<h1>New Performance Evaluation</h1>

<%= render 'form', performance_evaluation: @performance_evaluation %>

<%= link_to 'Back', performance_evaluations_path %>

app/views/performance_evaluations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>:</strong>
  <%= @performance_evaluation.title %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @performance_evaluation.due_date %>
</p>

<% @performance_evaluation.performance_commitments.each do |c| %>
  <%= c.commitment  %>
  <%= link_to 'ver', performance_commitment_comments_path(c.id) %>
<% end %>

<%= link_to 'Edit', edit_performance_evaluation_path(@performance_evaluation) %> |
<%= link_to 'Back', performance_evaluations_path %>